#! /bin/sh
rm `find -name "core*"`
rm `find -name "*.dat"`
rm `find -name "*.log"`
cd doc
sh make_docs
cd ..
make dist
cp surfit-2.1.tar.gz $HOME/rpm/SOURCES/
cat rpmmacros > $HOME/.rpmmacros
rpmbuild -ba surfit.spec.rh73
cp $HOME/rpm/SRPMS/surfit-2.1-rh73.src.rpm surfit-2.1-rh73.src.rpm
cp $HOME/rpm/RPMS/i386/surfit-2.1-rh73.i386.rpm surfit-2.1-rh73.i386.rpm


