Document: surfit
Title: Debian surfit Manual
Author: <insert document author here>
Abstract: This manual describes what surfit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/surfit/surfit.sgml.gz

Format: postscript
Files: /usr/share/doc/surfit/surfit.ps.gz

Format: text
Files: /usr/share/doc/surfit/surfit.text.gz

Format: HTML
Index: /usr/share/doc/surfit/html/index.html
Files: /usr/share/doc/surfit/html/*.html

  
