#! /bin/sh
rm `find -name "core*"`
rm `find -name "*.dat"`
rm `find -name "*.log"`
make dist
cp mklbooster-2.1.tar.gz $HOME/rpm/SOURCES/
cat rpmmacros > $HOME/.rpmmacros
rpmbuild -ba mklbooster.spec.rh73
cp $HOME/rpm/SRPMS/mklbooster-2.1-rh73.src.rpm mklbooster-2.1-rh73.src.rpm
cp $HOME/rpm/RPMS/i386/mklbooster-2.1-rh73.i386.rpm mklbooster-2.1-rh73.i386.rpm


