#! /bin/sh

rm html -rf
mkdir html

cp -l gallery/*.* html/
cp -l gallery/data/*.* html/
cp -l gallery/maps/*.* html/
cp -l gallery/globe/*.* html/

doxygen surfit.cfg

rm html/index.html
cp -lf src/index.html html/
cp -lf src/examples.html html/


