#! /bin/sh

rm -rf html
mkdir html

cp gallery/*.* html/
cp gallery/data/*.* html/
cp gallery/maps/*.* html/
cp gallery/globe/*.* html/

doxygen surfit.cfg

rm html/index.html
cp -lf src/index.html html/
cp -lf src/examples.html html/

