#! /bin/sh
rm `find -name core*`
rm `find -name *.dat`
make dist
cp acmlbooster-2.1.tar.gz $HOME/rpm/SOURCES/
cat rpmmacros > $HOME/.rpmmacros
rpmbuild -ba acmlbooster.spec.rh73
cp $HOME/rpm/SRPMS/acmlbooster-2.1-rh73.src.rpm acmlbooster-2.1-rh73.src.rpm
cp $HOME/rpm/RPMS/i386/acmlbooster-2.1-rh73.i386.rpm acmlbooster-2.1-rh73.i386.rpm


